//! XML tool-use recovery parser.
//!
//! Recovers `<tool_use id="..." name="...">{"json"}</tool_use>` and
//! Anthropic-style `<parameter name="...">` bodies from text delta
//! chunks that arrive incrementally from the upstream. Produces structured
//! `RecoveredCursorEvent` values for the bridge to emit as Anthropic tool_use
//! content blocks.

use std::collections::BTreeSet;
use std::fmt;

use crate::providers::cursor::request::{
    claude_tool_names_equivalent, is_text_editor_tool_name, preferred_text_editor_name,
};

/// An event recovered from a text delta chunk.
#[derive(Debug, Clone, PartialEq)]
pub enum RecoveredCursorEvent {
    Text(String),
    ToolUse(RecoveredCursorToolUse),
}

/// A recovered `<tool_use>` XML element.
#[derive(Debug, Clone, PartialEq)]
pub struct RecoveredCursorToolUse {
    /// Injected unique identifier (generated by the id factory, not from XML).
    pub id: String,
    /// The `id` attribute from the XML element, if present.
    pub original_id: Option<String>,
    /// The `name` attribute from the XML element.
    pub name: String,
    /// The parsed JSON input object.
    pub input: serde_json::Map<String, serde_json::Value>,
}

/// Parser that incrementally recovers `<tool_use>` XML elements from text
/// delta chunks.
pub struct CursorToolUseXmlParser {
    buffer: String,
    recovered_tool_use: bool,
    allowed_tool_names: Option<BTreeSet<String>>,
    id_factory: Box<dyn FnMut() -> String + Send>,
}

impl fmt::Debug for CursorToolUseXmlParser {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CursorToolUseXmlParser")
            .field("buffer", &self.buffer)
            .field("recovered_tool_use", &self.recovered_tool_use)
            .field("allowed_tool_names", &self.allowed_tool_names)
            .field("id_factory", &"<fn>")
            .finish()
    }
}

impl CursorToolUseXmlParser {
    /// Create a parser with the default UUID-based id factory.
    pub fn new(allowed_tool_names: Option<BTreeSet<String>>) -> Self {
        Self::new_with_id_factory(allowed_tool_names, default_id_factory())
    }

    /// Create a parser with a custom id factory for deterministic tests.
    pub fn new_with_id_factory(
        allowed_tool_names: Option<BTreeSet<String>>,
        id_factory: impl FnMut() -> String + Send + 'static,
    ) -> Self {
        Self {
            buffer: String::new(),
            recovered_tool_use: false,
            allowed_tool_names,
            id_factory: Box::new(id_factory),
        }
    }

    /// Whether any tool_use has been recovered so far.
    pub fn saw_tool_use(&self) -> bool {
        self.recovered_tool_use
    }

    /// Push a new text delta chunk and drain any complete events.
    pub fn push(&mut self, text: &str) -> Vec<RecoveredCursorEvent> {
        self.buffer.push_str(text);
        self.drain(false)
    }

    /// Flush any remaining buffered text, yielding any leftover events.
    pub fn flush(&mut self) -> Vec<RecoveredCursorEvent> {
        self.drain(true)
    }

    fn drain(&mut self, flush: bool) -> Vec<RecoveredCursorEvent> {
        let mut events: Vec<RecoveredCursorEvent> = Vec::new();

        loop {
            if self.buffer.is_empty() {
                break;
            }

            // Drop redundant *complete* close tags that can appear after
            // recovery. Incomplete prefixes must stay buffered so a split
            // `</assistant>` / `</tool_call>` does not leak `>`.
            if self.drop_redundant_close_tag() {
                continue;
            }

            // Look for the start of a <tool_use or <tool_call tag.
            let Some((start, kind)) = next_xml_tool_start(&self.buffer) else {
                // No tag start found: hold back a prefix of the buffer that
                // could be a partial marker, unless we are flushing.
                let hold = if flush {
                    0
                } else {
                    let mut hold = xml_tool_prefix_suffix_length(&self.buffer);
                    if self.recovered_tool_use {
                        hold = hold.max(xml_close_prefix_suffix_length(&self.buffer));
                    }
                    hold
                };
                let end = self.buffer.len().saturating_sub(hold);
                let text = self.buffer[..end].to_string();
                if !text.is_empty() {
                    self.push_text(&mut events, &text);
                }
                self.buffer = self.buffer[end..].to_string();
                break;
            };

            // Emit any text before the tag.
            if start > 0 {
                self.push_text(&mut events, &self.buffer[..start]);
                self.buffer = self.buffer[start..].to_string();
                continue;
            }

            let close = kind.close_tag();
            // Spawn prompts often paste inner `<tool_use>` examples. The first
            // `</tool_use>` is not the outer close; wait for depth zero.
            let close_start = find_matching_named_close(&self.buffer, kind.open_tag(), close);
            if close_start.is_none() {
                // Incomplete control markup must never become transcript text.
                // False prefixes such as `<tool_user>` stay visible.
                if flush {
                    if xml_tag_open_at(&self.buffer, 0, kind.open_tag()) {
                        self.buffer.clear();
                    } else {
                        self.push_text(&mut events, &self.buffer);
                        self.buffer.clear();
                    }
                }
                break;
            }

            let close_start = close_start.unwrap();
            let close_end = close_start + close.len();
            let raw = self.buffer[..close_end].to_string();

            if let Some(parsed) = self.parse_xml_tool(&raw, kind) {
                self.recovered_tool_use = true;
                events.push(RecoveredCursorEvent::ToolUse(parsed));
                self.buffer = self.buffer[close_end..].to_string();
            } else if kind == XmlToolKind::ToolCall
                && let Some((_, body)) = split_tagged_element(&raw, kind)
                && next_xml_tool_start(body).is_some()
            {
                // grok-cli wraps a fan-out of `<tool_use>` in one `<tool_call>`.
                // The wrapper is not itself a tool — unwrap and drain siblings.
                self.buffer = format!("{body}{}", &self.buffer[close_end..]);
            } else {
                // Complete but disallowed / unparsable control XML: drop it.
                self.buffer = self.buffer[close_end..].to_string();
            }
        }

        events
    }

    /// Try to parse a complete `<tool_use ...>...</tool_use>` element.
    fn parse_xml_tool(&mut self, raw: &str, kind: XmlToolKind) -> Option<RecoveredCursorToolUse> {
        match kind {
            XmlToolKind::ToolUse => self.parse_tool_use(raw),
            XmlToolKind::ToolCall => self.parse_tool_call(raw),
        }
    }

    fn parse_tool_use(&mut self, raw: &str) -> Option<RecoveredCursorToolUse> {
        let (attrs_str, body) = split_tagged_element(raw, XmlToolKind::ToolUse)?;
        let attrs = parse_xml_attributes(attrs_str);
        let name = attrs.get("name")?;
        let original_id = attrs.get("id").cloned();
        let original_id = if original_id.as_deref() == Some("") {
            None
        } else {
            original_id
        };

        let name = self.canonicalize_allowed_tool_name(name)?;

        let trimmed = body.trim();
        let input = if trimmed.is_empty() {
            serde_json::Map::new()
        } else if let Some(map) = parse_json_object(trimmed) {
            map
        } else {
            // grok-cli / Anthropic-style: <parameter name="...">value</parameter>
            parse_parameter_tags(trimmed)?
        };

        let id = (self.id_factory)();

        Some(RecoveredCursorToolUse {
            id,
            original_id,
            name,
            input,
        })
    }

    fn parse_tool_call(&mut self, raw: &str) -> Option<RecoveredCursorToolUse> {
        let (attrs_str, body) = split_tagged_element(raw, XmlToolKind::ToolCall)?;
        let attrs = parse_xml_attributes(attrs_str);
        let body = body.trim();
        let mut name = attrs.get("name").filter(|value| !value.is_empty()).cloned();
        let input = parse_tool_call_body(body, &mut name)?;
        let name = name.filter(|value| !value.is_empty())?;
        let name = self.canonicalize_allowed_tool_name(&name)?;
        Some(RecoveredCursorToolUse {
            id: (self.id_factory)(),
            original_id: None,
            name,
            input,
        })
    }

    fn canonicalize_allowed_tool_name(&self, name: &str) -> Option<String> {
        match &self.allowed_tool_names {
            Some(allowed) => {
                // Cursor's native PiEdit/XML bridge historically labels this
                // operation `Edit`, while Claude Code 2.1.x handles it under
                // the Anthropic-defined `str_replace_based_edit_tool` name.
                // When both spellings are present, select the modern handler
                // before the exact legacy hit; otherwise Claude Code reports
                // "Edit unavailable" and falls back to StrReplace.
                let editor_alias =
                    name.eq_ignore_ascii_case("Edit") || is_text_editor_tool_name(name);
                let modern_editor = editor_alias
                    .then(|| preferred_text_editor_name(allowed))
                    .flatten();
                modern_editor
                    .or_else(|| allowed.get(name).cloned())
                    .or_else(|| {
                        // Prefer the same built-in spelling (case-insensitively)
                        // when both a canonical name and a historical alias are
                        // advertised. This prevents a lower-cased `taskoutput`
                        // from being selected by BTreeSet order as AgentOutput.
                        if !is_case_insensitive_builtin_tool(name) {
                            return None;
                        }
                        allowed
                            .iter()
                            .find(|advertised| advertised.eq_ignore_ascii_case(name))
                            .cloned()
                    })
                    .or_else(|| {
                        // Claude Code keeps a handful of source-level aliases across
                        // releases (for example Workflow/RunWorkflow and
                        // Brief/SendUserMessage). XML-oriented models may emit the
                        // other spelling, so resolve only the explicit bounded alias
                        // families; arbitrary MCP names still require an exact match.
                        allowed
                            .iter()
                            .find(|advertised| claude_tool_names_equivalent(name, advertised))
                            .cloned()
                    })
            }
            None => Some(name.to_string()),
        }
    }

    /// Drop a redundant close tag that follows an already-
    /// recovered tool_use (the XML stream may contain duplicate close tags
    /// after recovery).
    fn drop_redundant_close_tag(&mut self) -> bool {
        if !self.recovered_tool_use {
            return false;
        }
        let trimmed_start = self.buffer.len() - self.buffer.trim_start().len();
        let slice = &self.buffer[trimmed_start..];
        for tag in ["</tool_use>", "</tool_call>", "</assistant>"] {
            if let Some(rest) = slice.strip_prefix(tag) {
                let prefix = &self.buffer[..trimmed_start];
                self.buffer = format!("{prefix}{rest}");
                return true;
            }
        }
        false
    }

    /// Push text into events, filtering empty text and trailing whitespace
    /// after a recovered tool_use.
    fn push_text(&self, events: &mut Vec<RecoveredCursorEvent>, text: &str) {
        if text.is_empty() {
            return;
        }
        if self.recovered_tool_use && text.trim().is_empty() {
            return;
        }
        events.push(RecoveredCursorEvent::Text(text.to_string()));
    }
}

fn is_case_insensitive_builtin_tool(name: &str) -> bool {
    // Only Claude-local tools are safe to recover case-insensitively.  Cursor
    // native names such as Read/Grep/Glob and Grok wire names are deliberately
    // excluded: accepting `Grep` for an advertised `grep` would turn a native
    // transcript fragment into a client tool call and bypass the native bridge.
    const CLAUDE_LOCAL_CASE_NAMES: &[&str] = &[
        "Agent",
        "Edit",
        "MultiEdit",
        "NotebookEdit",
        "str_replace_based_edit_tool",
        "str_replace_editor",
        "StrReplace",
        "StrReplaceTool",
        "NotebookRead",
        "PowerShell",
        "Task",
        "TaskCreate",
        "TaskGet",
        "TaskUpdate",
        "TaskList",
        "TaskStop",
        "AgentOutputTool",
        "BashOutputTool",
        "AgentOutput",
        "BashOutput",
        "KillShell",
        "KillBash",
        "ListPeers",
        "EnterPlanMode",
        "ExitPlanMode",
        "EnterWorktree",
        "ExitWorktree",
        "LSP",
        "CronCreate",
        "CronDelete",
        "CronList",
        "ScheduleWakeup",
        "RemoteTrigger",
        "SendMessage",
        "Brief",
        "ToolSearch",
        "ListMcpResourcesTool",
        "ReadMcpResourceTool",
        "ReadMcpResourceDirTool",
        "ListMcpResources",
        "ReadMcpResource",
        "ReadMcpResourceDir",
        "ListAgents",
        "WaitForMcpServers",
        "SendUserMessage",
        "SendUserFile",
        "ReportFindings",
        "TaskOutput",
        "Monitor",
        "StructuredOutput",
        "TestingPermission",
        "Artifact",
        "REPL",
        "RefreshMcpTools",
        "PushNotification",
        "DesignSync",
        "Projects",
        "ShareOnboardingGuide",
        "ClaudeDesign",
        "ShowOnboardingRolePicker",
        "ConnectGitHub",
        "EndConversation",
        "SendFile",
        "SearchMcpRegistry",
        "SuggestConnectors",
        "ListConnectors",
        "Workflow",
        "RunWorkflow",
        "Skill",
    ];
    CLAUDE_LOCAL_CASE_NAMES
        .iter()
        .any(|candidate| candidate.eq_ignore_ascii_case(name))
}

fn default_id_factory() -> Box<dyn FnMut() -> String + Send> {
    Box::new(|| {
        let id = uuid::Uuid::new_v4().to_string().replace('-', "");
        format!("call_cursor_{id}")
    })
}

// ---------------------------------------------------------------------------
// XML attribute parsing
// ---------------------------------------------------------------------------

fn parse_xml_attributes(source: &str) -> std::collections::HashMap<String, String> {
    let mut attrs = std::collections::HashMap::new();
    let re = regex_lite::Regex::new(r#"([A-Za-z_][\w:.-]*)\s*=\s*(?:"([^"]*)"|'([^']*)')"#).ok();
    let re = match re {
        Some(r) => r,
        None => return attrs,
    };
    for cap in re.captures_iter(source) {
        let key = cap.get(1).map(|m| m.as_str()).unwrap_or("");
        let value = cap
            .get(2)
            .or_else(|| cap.get(3))
            .map(|m| m.as_str())
            .unwrap_or("");
        if !key.is_empty() {
            attrs.insert(key.to_string(), decode_xml_attribute(value));
        }
    }
    attrs
}

fn decode_xml_attribute(value: &str) -> String {
    value
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum XmlToolKind {
    ToolUse,
    ToolCall,
}

impl XmlToolKind {
    fn open_tag(self) -> &'static str {
        match self {
            Self::ToolUse => "<tool_use",
            Self::ToolCall => "<tool_call",
        }
    }

    fn close_tag(self) -> &'static str {
        match self {
            Self::ToolUse => "</tool_use>",
            Self::ToolCall => "</tool_call>",
        }
    }
}

fn split_tagged_element(raw: &str, kind: XmlToolKind) -> Option<(&str, &str)> {
    let open = kind.open_tag();
    let close = kind.close_tag();
    if !raw.starts_with(open) || !raw.ends_with(close) {
        return None;
    }
    let gt = raw.find('>')?;
    let attrs = &raw[open.len()..gt];
    let body = &raw[gt + 1..raw.len() - close.len()];
    Some((attrs, body))
}

/// True when `buffer[at..]` is an XML start tag for `open` (`<tool_use`,
/// `<parameter`, …), not a longer name like `<tool_user`.
fn xml_tag_open_at(buffer: &str, at: usize, open: &str) -> bool {
    let Some(rest) = buffer.get(at..) else {
        return false;
    };
    if !rest.starts_with(open) {
        return false;
    }
    match rest[open.len()..].chars().next() {
        Some('>' | '/' | ' ' | '\t' | '\n' | '\r') => true,
        Some(c) if c.is_ascii_alphanumeric() || c == '_' || c == '-' => false,
        Some(_) => true,
        None => false,
    }
}

/// Index of the matching close tag for an element that starts at `buffer[0]`.
fn find_matching_named_close(buffer: &str, open: &str, close: &str) -> Option<usize> {
    if !xml_tag_open_at(buffer, 0, open) {
        return None;
    }
    let open_gt = buffer.find('>')?;
    let mut depth = 1i32;
    let mut i = open_gt + 1;
    while i < buffer.len() {
        if buffer.get(i..).is_some_and(|rest| rest.starts_with(close)) {
            depth -= 1;
            if depth == 0 {
                return Some(i);
            }
            i += close.len();
            continue;
        }
        if xml_tag_open_at(buffer, i, open) {
            depth += 1;
            i += open.len();
            continue;
        }
        i += buffer[i..].chars().next()?.len_utf8();
    }
    None
}

fn next_xml_tool_start(buffer: &str) -> Option<(usize, XmlToolKind)> {
    let tool_use = buffer.find("<tool_use");
    let tool_call = buffer.find("<tool_call");
    match (tool_use, tool_call) {
        (Some(use_at), Some(call_at)) if use_at <= call_at => Some((use_at, XmlToolKind::ToolUse)),
        (Some(_), Some(call_at)) => Some((call_at, XmlToolKind::ToolCall)),
        (Some(use_at), None) => Some((use_at, XmlToolKind::ToolUse)),
        (None, Some(call_at)) => Some((call_at, XmlToolKind::ToolCall)),
        (None, None) => None,
    }
}

fn parse_tool_call_body(
    body: &str,
    name: &mut Option<String>,
) -> Option<serde_json::Map<String, serde_json::Value>> {
    let trimmed = body.trim();
    if trimmed.is_empty() {
        return Some(serde_json::Map::new());
    }
    if let Some(object) = parse_json_object(trimmed) {
        return tool_call_input_from_object(object, name);
    }
    let ident = regex_lite::Regex::new(r"^([A-Za-z_][\w.-]*)\s*([\s\S]*)$").ok()?;
    let caps = ident.captures(trimmed)?;
    if name.as_ref().is_none_or(|value| value.is_empty()) {
        *name = Some(caps.get(1)?.as_str().to_string());
    }
    let rest = caps.get(2).map(|m| m.as_str()).unwrap_or("").trim();
    if rest.is_empty() {
        return Some(serde_json::Map::new());
    }
    if let Some(object) = parse_json_object(rest) {
        return tool_call_input_from_object(object, name);
    }
    parse_parameter_tags(rest)
}

fn tool_call_input_from_object(
    mut object: serde_json::Map<String, serde_json::Value>,
    name: &mut Option<String>,
) -> Option<serde_json::Map<String, serde_json::Value>> {
    if name.as_ref().is_none_or(|value| value.is_empty())
        && let Some(n) = object.get("name").and_then(serde_json::Value::as_str)
        && !n.is_empty()
    {
        *name = Some(n.to_string());
    }
    if let Some(args) = object
        .get("arguments")
        .or_else(|| object.get("parameters"))
        .cloned()
    {
        return match args {
            serde_json::Value::Object(map) => Some(map),
            other => {
                let mut wrapped = serde_json::Map::new();
                wrapped.insert("input".into(), other);
                Some(wrapped)
            }
        };
    }
    object.remove("name");
    Some(object)
}

fn parse_parameter_tags(body: &str) -> Option<serde_json::Map<String, serde_json::Value>> {
    const OPEN: &str = "<parameter";
    const CLOSE: &str = "</parameter>";
    let mut map = serde_json::Map::new();
    let mut found = false;
    let mut i = 0;
    while i < body.len() {
        let Some(rel) = body[i..].find(OPEN) else {
            break;
        };
        let start = i + rel;
        if !xml_tag_open_at(body, start, OPEN) {
            i = start + OPEN.len();
            continue;
        }
        let close_at = find_matching_named_close(&body[start..], OPEN, CLOSE)?;
        let end = start + close_at + CLOSE.len();
        let elem = &body[start..end];
        let gt = elem.find('>')?;
        let attrs = parse_xml_attributes(&elem[OPEN.len()..gt]);
        let raw = elem[gt + 1..elem.len() - CLOSE.len()].trim();
        let value = match serde_json::from_str::<serde_json::Value>(raw) {
            Ok(parsed) => parsed,
            Err(_) => serde_json::Value::String(raw.to_string()),
        };
        if let Some(param_name) = attrs.get("name").filter(|value| !value.is_empty()) {
            map.insert(param_name.clone(), value);
        } else if let serde_json::Value::Object(object) = value {
            return Some(object);
        } else {
            map.insert("input".into(), value);
        }
        found = true;
        i = end;
    }
    found.then_some(map)
}

fn parse_json_object(raw: &str) -> Option<serde_json::Map<String, serde_json::Value>> {
    match serde_json::from_str::<serde_json::Value>(raw.trim()) {
        Ok(serde_json::Value::Object(map)) => Some(map),
        _ => None,
    }
}

/// Compute how many characters at the end of `value` could be a partial
/// `<tool_use` / `<tool_call` marker.
fn xml_tool_prefix_suffix_length(value: &str) -> usize {
    prefix_suffix_length(value, "<tool_use").max(prefix_suffix_length(value, "<tool_call"))
}

fn xml_close_prefix_suffix_length(value: &str) -> usize {
    ["</tool_use>", "</tool_call>", "</assistant>"]
        .into_iter()
        .map(|marker| prefix_suffix_length(value, marker))
        .max()
        .unwrap_or(0)
}

fn prefix_suffix_length(value: &str, marker: &str) -> usize {
    let max = marker.len().saturating_sub(1).min(value.len());
    for len in (1..=max).rev() {
        if value.ends_with(&marker[..len]) {
            return len;
        }
    }
    0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_id_factory() -> Box<dyn FnMut() -> String + Send> {
        let mut counter = 0u64;
        Box::new(move || {
            counter += 1;
            format!("call_cursor_test_{counter}")
        })
    }

    #[test]
    fn recovers_complete_tool_use_xml() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let input = r#"before <tool_use id="x" name="Read">{"file_path":"a"}</tool_use> after"#;
        let events = parser.push(input);
        assert_eq!(events.len(), 3);
        assert_eq!(events[0], RecoveredCursorEvent::Text("before ".into()));
        assert!(matches!(&events[1], RecoveredCursorEvent::ToolUse(tool) if tool.name == "Read"));
        assert_eq!(events[2], RecoveredCursorEvent::Text(" after".into()));
        assert!(parser.saw_tool_use());
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn recovers_split_tool_use_xml() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        assert_eq!(
            parser.push("before <tool_"),
            vec![RecoveredCursorEvent::Text("before ".into())]
        );
        let events = parser.push(r#"use id="x" name="Read">{"file_path":"a"}</tool_use> after"#);
        assert!(matches!(&events[0], RecoveredCursorEvent::ToolUse(tool) if tool.name == "Read"));
        assert_eq!(events[1], RecoveredCursorEvent::Text(" after".into()));
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn split_tool_xml_preserves_adjacent_unicode_without_leaking_markup() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Edit".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let mut events = parser.push("前缀🙂 <tool_");
        events.extend(parser.push(concat!(
            r#"use name="Edit">{"file_path":"a","old_string":"旧","new_string":"新"}"#,
            "</tool_use> 后缀✅",
        )));
        events.extend(parser.flush());

        let visible = events
            .iter()
            .filter_map(|event| match event {
                RecoveredCursorEvent::Text(text) => Some(text.as_str()),
                RecoveredCursorEvent::ToolUse(_) => None,
            })
            .collect::<String>();
        assert_eq!(visible, "前缀🙂  后缀✅");
        assert!(matches!(
            events
                .iter()
                .find(|event| matches!(event, RecoveredCursorEvent::ToolUse(_))),
            Some(RecoveredCursorEvent::ToolUse(tool))
                if tool.name == "Edit"
                    && tool.input["old_string"] == "旧"
                    && tool.input["new_string"] == "新"
        ));
        assert!(events.iter().all(|event| match event {
            RecoveredCursorEvent::Text(text) => {
                !text.contains("<tool_") && !text.contains("</tool_")
            }
            RecoveredCursorEvent::ToolUse(_) => true,
        }));
    }

    #[test]
    fn recovers_tool_use_without_original_id() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(r#"<tool_use name="Read">{"x":1}</tool_use>"#);
        assert_eq!(events.len(), 1);
        if let RecoveredCursorEvent::ToolUse(tool) = &events[0] {
            assert_eq!(tool.original_id, None);
            assert_eq!(tool.name, "Read");
            assert_eq!(tool.input.get("x").and_then(|v| v.as_i64()), Some(1));
        } else {
            panic!("expected ToolUse");
        }
    }

    #[test]
    fn recovers_tool_use_with_original_id() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Write".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(
            r#"<tool_use id="orig-1" name="Write">{"file_path":"b","content":"hi"}</tool_use>"#,
        );
        assert_eq!(events.len(), 1);
        if let RecoveredCursorEvent::ToolUse(tool) = &events[0] {
            assert_eq!(tool.original_id.as_deref(), Some("orig-1"));
            assert_eq!(tool.name, "Write");
        } else {
            panic!("expected ToolUse");
        }
    }

    #[test]
    fn canonicalizes_case_variant_for_known_builtin_tools() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Edit".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(r#"<tool_use name="edit">{"file_path":"a"}</tool_use>"#);
        assert!(matches!(
            &events[..],
            [RecoveredCursorEvent::ToolUse(tool)] if tool.name == "Edit"
        ));
    }

    #[test]
    fn canonicalizes_new_claude_builtin_case_variants() {
        for (wire_name, advertised_name) in [
            ("taskoutput", "TaskOutput"),
            ("monitor", "Monitor"),
            ("structuredoutput", "StructuredOutput"),
            ("artifact", "Artifact"),
            ("repl", "REPL"),
            ("designsync", "DesignSync"),
            ("projects", "Projects"),
            ("pushnotification", "PushNotification"),
            ("connectgithub", "ConnectGitHub"),
            ("brief", "Brief"),
            ("testingpermission", "TestingPermission"),
            ("runworkflow", "RunWorkflow"),
            ("listpeers", "ListPeers"),
            ("readmcpresource", "ReadMcpResource"),
        ] {
            let mut parser = CursorToolUseXmlParser::new_with_id_factory(
                Some([advertised_name.to_string()].into_iter().collect()),
                test_id_factory(),
            );
            let xml = format!(r#"<tool_use name="{wire_name}">{{}}</tool_use>"#);
            let events = parser.push(&xml);
            assert!(
                matches!(&events[..], [RecoveredCursorEvent::ToolUse(tool)] if tool.name == advertised_name),
                "{wire_name} should recover as {advertised_name}: {events:?}"
            );
        }
    }

    #[test]
    fn canonicalizes_claude_runtime_aliases_to_advertised_spelling() {
        for (wire_name, advertised_name) in [
            ("Workflow", "RunWorkflow"),
            ("RunWorkflow", "Workflow"),
            ("Brief", "SendUserMessage"),
            ("SendUserMessage", "Brief"),
            ("ListPeers", "ListAgents"),
            ("ListMcpResources", "ListMcpResourcesTool"),
            ("ReadMcpResource", "ReadMcpResourceTool"),
            ("ReadMcpResourceDir", "ReadMcpResourceDirTool"),
        ] {
            let mut parser = CursorToolUseXmlParser::new_with_id_factory(
                Some([advertised_name.to_string()].into_iter().collect()),
                test_id_factory(),
            );
            let xml = format!(r#"<tool_use name="{wire_name}">{{}}</tool_use>"#);
            let events = parser.push(&xml);
            assert!(
                matches!(&events[..], [RecoveredCursorEvent::ToolUse(tool)] if tool.name == advertised_name),
                "{wire_name} should recover as {advertised_name}: {events:?}"
            );
        }
    }

    #[test]
    fn canonicalizes_lowercase_to_same_spelling_before_alias_fallback() {
        let allowed = ["AgentOutput".to_string(), "TaskOutput".to_string()]
            .into_iter()
            .collect();
        let mut parser =
            CursorToolUseXmlParser::new_with_id_factory(Some(allowed), test_id_factory());
        let events = parser.push(r#"<tool_use name="taskoutput">{}</tool_use>"#);
        assert!(matches!(
            &events[..],
            [RecoveredCursorEvent::ToolUse(tool)] if tool.name == "TaskOutput"
        ));
    }

    #[test]
    fn filters_disallowed_tool_names() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        // Bash is not in allowed set, so the markup is dropped.
        let events = parser.push(r#"<tool_use id="x" name="Bash">{"command":"pwd"}</tool_use>"#);
        assert!(
            events.is_empty(),
            "disallowed tool XML must be quarantined: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn invalid_json_fallback_to_text() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(r#"<tool_use id="x" name="Read">{invalid}</tool_use>"#);
        assert!(
            events.is_empty(),
            "invalid tool input must be quarantined: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn redundant_close_tag_after_recovery() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        // First recover a tool_use.
        let events = parser.push(r#"<tool_use name="Read">{}</tool_use>"#);
        assert_eq!(events.len(), 1);
        assert!(parser.saw_tool_use());

        // Push a redundant close tag (common in streaming XML).
        let events = parser.push("</tool_use>");
        // Should be silently dropped, no text events.
        assert!(events.is_empty());
    }

    #[test]
    fn flush_returns_remaining_text() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        // Push an incomplete tag.
        let events = parser.push("some text <tool_use name=\"Read\">{\"a\":1}");
        // No close tag yet, so only text before partial tag should emit.
        // But the parser holds back the partial prefix, so "some text " emits.
        assert_eq!(events.len(), 1);
        assert_eq!(events[0], RecoveredCursorEvent::Text("some text ".into()));

        // Flush must drop incomplete control markup instead of leaking it.
        let events = parser.flush();
        assert!(
            !leaked_raw_xml(&events),
            "incomplete <tool_use> on flush must not leak: {events:?}"
        );
    }

    #[test]
    fn empty_push_does_nothing() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(None, test_id_factory());
        let events = parser.push("");
        assert!(events.is_empty());
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn text_only_chunks() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(None, test_id_factory());
        assert_eq!(
            parser.push("hello world"),
            vec![RecoveredCursorEvent::Text("hello world".into())]
        );
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn multiple_tool_uses_in_one_push() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(
                ["Read".to_string(), "Write".to_string()]
                    .into_iter()
                    .collect(),
            ),
            test_id_factory(),
        );
        let events = parser.push(
            r#"<tool_use name="Read">{"file_path":"a"}</tool_use><tool_use name="Write">{"file_path":"b","content":"c"}</tool_use>"#,
        );
        assert_eq!(events.len(), 2);
        assert!(matches!(&events[0], RecoveredCursorEvent::ToolUse(t) if t.name == "Read"));
        assert!(matches!(&events[1], RecoveredCursorEvent::ToolUse(t) if t.name == "Write"));
    }

    #[test]
    fn parse_xml_attributes_extracts_name_and_id() {
        let attrs = parse_xml_attributes(r#"id="abc" name="Read""#);
        assert_eq!(attrs.get("name").map(|s| s.as_str()), Some("Read"));
        assert_eq!(attrs.get("id").map(|s| s.as_str()), Some("abc"));
    }

    #[test]
    fn parse_xml_handles_single_quotes() {
        let attrs = parse_xml_attributes(r#"name='Read'"#);
        assert_eq!(attrs.get("name").map(|s| s.as_str()), Some("Read"));
    }

    #[test]
    fn parse_xml_decodes_entities() {
        let attrs = parse_xml_attributes(r#"name="Read &amp; Write""#);
        assert_eq!(attrs.get("name").map(|s| s.as_str()), Some("Read & Write"));
    }

    #[test]
    fn xml_tool_prefix_suffix_identifies_partial_tag() {
        assert_eq!(xml_tool_prefix_suffix_length("<tool_"), 6);
        assert_eq!(xml_tool_prefix_suffix_length("<tool_us"), 8);
        assert_eq!(xml_tool_prefix_suffix_length("<tool_ca"), 8);
        assert_eq!(xml_tool_prefix_suffix_length("hello <tool_"), 6);
        assert_eq!(xml_tool_prefix_suffix_length("hello"), 0);
        assert_eq!(xml_tool_prefix_suffix_length("<"), 1);
    }

    #[test]
    fn saw_tool_use_starts_false() {
        let parser = CursorToolUseXmlParser::new_with_id_factory(None, test_id_factory());
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn empty_input_after_flush() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(None, test_id_factory());
        let events = parser.push("hello");
        assert_eq!(events.len(), 1);
        // Flush with no partial tag should be empty.
        assert!(parser.flush().is_empty());
        // Another flush should also be empty.
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn recovers_grok_tool_call_with_unnamed_parameter_json() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["todo_write".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let input = concat!(
            "调查已经齐了。\n",
            r#"<tool_call> todo_write <parameter> {"todos":[{"id":"1","content":"\u91cd\u8bd5","status":"completed"}]} </parameter> </tool_call>"#,
            " </assistant>"
        );
        let events = parser.push(input);
        assert!(
            events
                .iter()
                .any(|event| matches!(event, RecoveredCursorEvent::ToolUse(tool) if tool.name == "todo_write")),
            "grok <tool_call> todo_write must become a structured tool, got {events:?}"
        );
        assert!(
            !events.iter().any(|event| matches!(
                event,
                RecoveredCursorEvent::Text(text)
                    if text.contains("<tool_call")
                        || text.contains("</tool_call>")
                        || text.contains("</assistant>")
            )),
            "raw grok tool XML and chat-template close tags must not leak as text: {events:?}"
        );
        let RecoveredCursorEvent::ToolUse(tool) = events
            .iter()
            .find(|event| matches!(event, RecoveredCursorEvent::ToolUse(_)))
            .unwrap()
        else {
            unreachable!();
        };
        assert_eq!(
            tool.input["todos"][0]["content"].as_str(),
            Some("重试"),
            "JSON unicode escapes inside <parameter> must decode: {:?}",
            tool.input
        );
        assert!(parser.saw_tool_use());
    }

    #[test]
    fn recovers_split_grok_tool_call_xml() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["todo_write".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let first = parser.push("ok <tool_");
        assert_eq!(first, vec![RecoveredCursorEvent::Text("ok ".into())]);
        let events = parser
            .push(r#"call> todo_write <parameter>{"todos":[]}</parameter></tool_call> after"#);
        assert!(matches!(
            &events[0],
            RecoveredCursorEvent::ToolUse(tool) if tool.name == "todo_write"
        ));
        assert_eq!(events[1], RecoveredCursorEvent::Text(" after".into()));
    }

    #[test]
    fn grok_tool_call_disallowed_name_stays_text() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["read_file".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser
            .push(r#"<tool_call> todo_write <parameter> {"todos":[]} </parameter> </tool_call>"#);
        assert!(
            events.is_empty(),
            "disallowed <tool_call> must be quarantined: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn split_assistant_close_tag_is_held_until_complete() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["todo_write".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let first = parser.push(concat!(
            r#"<tool_call> todo_write <parameter> {"todos":[]} </parameter> </tool_call>"#,
            "</assistant",
        ));
        assert!(
            first.iter().any(|event| matches!(
                event,
                RecoveredCursorEvent::ToolUse(tool) if tool.name == "todo_write"
            )),
            "tool_call must recover before the split closer: {first:?}"
        );
        assert!(
            !first.iter().any(|event| matches!(
                event,
                RecoveredCursorEvent::Text(text) if text.contains("assistant") || text == ">"
            )),
            "incomplete </assistant must not leak or be stripped early: {first:?}"
        );
        let rest = parser.push(">");
        assert!(
            rest.is_empty(),
            "completing </assistant> must not emit leftover text: {rest:?}"
        );
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn assistant_close_prefix_does_not_eat_unrelated_text() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["todo_write".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(concat!(
            r#"<tool_call> todo_write <parameter> {"todos":[]} </parameter> </tool_call>"#,
            "</assistant_note>",
        ));
        assert!(
            events.iter().any(|event| matches!(
                event,
                RecoveredCursorEvent::Text(text) if text.contains("</assistant_note>")
            )),
            "only the exact </assistant> closer is redundant: {events:?}"
        );
    }

    fn leaked_raw_xml(events: &[RecoveredCursorEvent]) -> bool {
        events.iter().any(|event| {
            matches!(
                event,
                RecoveredCursorEvent::Text(text)
                    if text.contains("<tool_use")
                        || text.contains("</tool_use>")
                        || text.contains("<tool_call")
                        || text.contains("</tool_call>")
                        || text.contains("<parameter")
            )
        })
    }

    #[test]
    fn recovers_tool_use_with_named_parameter_tags() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["spawn_subagent".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let input = concat!(
            r#"<tool_use id="spawn-40" name="spawn_subagent">"#,
            r#"<parameter name="background">true</parameter>"#,
            r#"<parameter name="description">CARVE A1560 0013 REREAD_1</parameter>"#,
            r#"<parameter name="prompt">Read 40.txt completely. Do not read any other path.</parameter>"#,
            r#"<parameter name="subagent_type">general-purpose</parameter>"#,
            "</tool_use>",
            " </tool_call>",
        );
        let events = parser.push(input);
        assert_eq!(
            events
                .iter()
                .filter(|event| matches!(event, RecoveredCursorEvent::ToolUse(_)))
                .count(),
            1,
            "named <parameter> children must become one spawn_subagent: {events:?}"
        );
        assert!(
            !leaked_raw_xml(&events),
            "raw <tool_use>/<parameter> XML must not leak as transcript: {events:?}"
        );
        let RecoveredCursorEvent::ToolUse(tool) = events
            .iter()
            .find(|event| matches!(event, RecoveredCursorEvent::ToolUse(_)))
            .unwrap()
        else {
            unreachable!();
        };
        assert_eq!(tool.name, "spawn_subagent");
        assert_eq!(tool.original_id.as_deref(), Some("spawn-40"));
        assert_eq!(tool.input["background"], true);
        assert_eq!(tool.input["description"], "CARVE A1560 0013 REREAD_1");
        assert_eq!(
            tool.input["prompt"].as_str(),
            Some("Read 40.txt completely. Do not read any other path.")
        );
        assert_eq!(tool.input["subagent_type"], "general-purpose");
        assert!(parser.flush().is_empty());
    }

    #[test]
    fn recovers_outer_tool_use_when_prompt_contains_nested_xml() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["spawn_subagent".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let input = concat!(
            r#"<tool_use name="spawn_subagent">"#,
            r#"<parameter name="background">true</parameter>"#,
            r#"<parameter name="description">outer</parameter>"#,
            r#"<parameter name="prompt">"#,
            "follow 40.txt. nested example: ",
            r#"<parameter name="subagent_type">general-purpose</parameter>"#,
            r#"<tool_use id="spawn-41" name="spawn_subagent">"#,
            r#"<parameter name="prompt">inner</parameter>"#,
            "</tool_use>",
            " done",
            "</parameter>",
            "</tool_use>",
        );
        let events = parser.push(input);
        let tools: Vec<_> = events
            .iter()
            .filter_map(|event| match event {
                RecoveredCursorEvent::ToolUse(tool) => Some(tool),
                RecoveredCursorEvent::Text(_) => None,
            })
            .collect();
        assert_eq!(
            tools.len(),
            1,
            "nested tool XML inside prompt must not become a second tool: {events:?}"
        );
        assert!(
            !leaked_raw_xml(&events),
            "nested XML belongs in the prompt field, not transcript: {events:?}"
        );
        assert_eq!(tools[0].name, "spawn_subagent");
        assert_eq!(tools[0].input["description"], "outer");
        let prompt = tools[0].input["prompt"].as_str().unwrap();
        assert!(
            prompt.contains("follow 40.txt"),
            "outer prompt must keep leading text: {prompt:?}"
        );
        assert!(
            prompt.contains("spawn-41") && prompt.contains("</tool_use>"),
            "inner tool XML must stay inside prompt: {prompt:?}"
        );
        assert!(
            prompt.contains("done"),
            "outer prompt must keep trailing text after nested XML: {prompt:?}"
        );
    }

    #[test]
    fn named_parameter_tool_use_disallowed_name_stays_text() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["read_file".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(concat!(
            r#"<tool_use name="spawn_subagent">"#,
            r#"<parameter name="prompt">secret</parameter>"#,
            "</tool_use>",
        ));
        assert!(
            events.is_empty(),
            "disallowed named-parameter tool_use must be quarantined: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn recovers_multiple_tool_uses_wrapped_in_tool_call() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(
                [
                    "read_file".to_string(),
                    "get_command_or_subagent_output".to_string(),
                    "run_terminal_command".to_string(),
                ]
                .into_iter()
                .collect(),
            ),
            test_id_factory(),
        );
        let input = concat!(
            "<tool_call>",
            r#"<tool_use id="read-workflow-skill" name="read_file">"#,
            r#"<parameter name="path">/Users/yeauty/.grok/bundled/skills/create-workflow/SKILL.md</parameter>"#,
            "</tool_use>",
            r#"<tool_use id="get-07" name="get_command_or_subagent_output">"#,
            r#"<parameter name="task_id">01a01550-751c-7fc1-82ff-28b2e7e64844</parameter>"#,
            r#"<parameter name="timeout_ms">0</parameter>"#,
            "</tool_use>",
            r#"<tool_use id="dump-launch" name="run_terminal_command">"#,
            r#"<parameter name="command">python3 -c 'print(1)'</parameter>"#,
            r#"<parameter name="description">Dump progress</parameter>"#,
            "</tool_use>",
            r#"<tool_use id="find-workflow-examples" name="Glob">"#,
            r#"<parameter name="glob_pattern">**/*.rhai</parameter>"#,
            r#"<parameter name="target_directory">/Users/yeauty/.grok</parameter>"#,
            "</tool_use>",
            "</tool_call>",
        );
        let events = parser.push(input);
        let names: Vec<_> = events
            .iter()
            .filter_map(|event| match event {
                RecoveredCursorEvent::ToolUse(tool) => Some(tool.name.as_str()),
                RecoveredCursorEvent::Text(_) => None,
            })
            .collect();
        assert_eq!(
            names,
            [
                "read_file",
                "get_command_or_subagent_output",
                "run_terminal_command"
            ],
            "wrapper <tool_call> must unwrap into sibling tool_use: {events:?}"
        );
        assert!(
            !leaked_raw_xml(&events),
            "wrapper and unadvertised Glob XML must not leak: {events:?}"
        );
        assert!(
            !names.contains(&"Glob"),
            "must not invent a Glob tool the client did not advertise"
        );
    }

    fn grok_shell_allowlist() -> BTreeSet<String> {
        [
            "run_terminal_command".to_string(),
            "read_file".to_string(),
            "get_command_or_subagent_output".to_string(),
        ]
        .into_iter()
        .collect()
    }

    fn recovered_names(events: &[RecoveredCursorEvent]) -> Vec<&str> {
        events
            .iter()
            .filter_map(|event| match event {
                RecoveredCursorEvent::ToolUse(tool) => Some(tool.name.as_str()),
                RecoveredCursorEvent::Text(_) => None,
            })
            .collect()
    }

    #[test]
    fn disallowed_tool_xml_is_quarantined_not_transcript() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(r#"<tool_use id="x" name="Bash">{"command":"pwd"}</tool_use>"#);
        assert!(
            !leaked_raw_xml(&events),
            "disallowed <tool_use> must not become transcript text: {events:?}"
        );
        assert!(
            recovered_names(&events).is_empty(),
            "must not execute a tool the client did not advertise: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn invalid_tool_input_xml_is_quarantined_not_transcript() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(r#"<tool_use id="x" name="Read">{invalid}</tool_use>"#);
        assert!(
            !leaked_raw_xml(&events),
            "malformed tool input must not leak as transcript XML: {events:?}"
        );
        assert!(
            recovered_names(&events).is_empty(),
            "must not invent a tool from invalid JSON: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn flush_incomplete_tool_use_does_not_leak_xml() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["Read".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push("some text <tool_use name=\"Read\">{\"a\":1}");
        assert_eq!(
            events,
            vec![RecoveredCursorEvent::Text("some text ".into())]
        );
        let flushed = parser.flush();
        assert!(
            !leaked_raw_xml(&flushed),
            "incomplete <tool_use> on flush must not leak: {flushed:?}"
        );
        assert!(
            recovered_names(&flushed).is_empty(),
            "incomplete markup must not become a tool: {flushed:?}"
        );
    }

    #[test]
    fn unadvertised_glob_xml_is_quarantined_not_invented() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(grok_shell_allowlist()),
            test_id_factory(),
        );
        let events = parser.push(concat!(
            r#"<tool_use id="glob-rhai" name="Glob">"#,
            r#"<parameter name="glob_pattern">**/*.rhai</parameter>"#,
            r#"<parameter name="target_directory">/Users/yeauty/.grok/bundled/skills/create-workflow</parameter>"#,
            "</tool_use>",
        ));
        assert!(
            !leaked_raw_xml(&events),
            "unadvertised Cursor Glob XML must not appear in transcript: {events:?}"
        );
        assert!(
            !recovered_names(&events).contains(&"Glob"),
            "must not invent Glob: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn malformed_unclosed_parameter_is_quarantined() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(grok_shell_allowlist()),
            test_id_factory(),
        );
        // Capture from grok-cli 0.1.51: command parameter never closes.
        let events = parser.push(concat!(
            r#"<tool_use id="dump-and-collect" name="run_terminal_command">"#,
            "<parameter name=\"command\">python3 -c <<'PY'\n",
            "print(1)\n",
            "PY\n",
            r#"<parameter name="description">Dump progress, in-flight, launch pack</parameter>"#,
            "</tool_use>",
        ));
        assert!(
            !leaked_raw_xml(&events),
            "malformed run_terminal_command XML must not leak: {events:?}"
        );
        assert!(
            recovered_names(&events).is_empty(),
            "must not execute a tool whose parameters did not parse: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }

    #[test]
    fn recovers_closed_heredoc_run_terminal_command() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(grok_shell_allowlist()),
            test_id_factory(),
        );
        let events = parser.push(concat!(
            r#"<tool_use id="dump-and-collect" name="run_terminal_command">"#,
            "<parameter name=\"command\">python3 -c <<'PY'\n",
            "print(1)\n",
            "PY\n",
            "</parameter>",
            r#"<parameter name="description">Dump progress, in-flight, launch pack</parameter>"#,
            "</tool_use>",
        ));
        assert!(
            !leaked_raw_xml(&events),
            "closed heredoc command must not leak XML: {events:?}"
        );
        assert_eq!(recovered_names(&events), ["run_terminal_command"]);
        let RecoveredCursorEvent::ToolUse(tool) = &events[0] else {
            panic!("expected recovered shell tool: {events:?}");
        };
        assert_eq!(
            tool.input["command"].as_str(),
            Some("python3 -c <<'PY'\nprint(1)\nPY")
        );
        assert_eq!(
            tool.input["description"].as_str(),
            Some("Dump progress, in-flight, launch pack")
        );
    }

    #[test]
    fn xml_workflow_recovers_as_advertised_grok_name() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["workflow".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(
            r#"<tool_use id="wf" name="Workflow"><parameter name="name">carve-bind-wave64</parameter><parameter name="agent_budget">80</parameter></tool_use>"#,
        );
        assert!(
            !leaked_raw_xml(&events),
            "Workflow XML must not leak when grok advertised workflow: {events:?}"
        );
        assert_eq!(recovered_names(&events), ["workflow"]);
        let RecoveredCursorEvent::ToolUse(tool) = &events[0] else {
            panic!("expected recovered workflow: {events:?}");
        };
        assert_eq!(tool.input["name"].as_str(), Some("carve-bind-wave64"));
        assert_eq!(tool.input["agent_budget"], 80);
    }

    #[test]
    fn case_insensitive_recovery_does_not_invent_cursor_native_tools() {
        let mut parser = CursorToolUseXmlParser::new_with_id_factory(
            Some(["grep".to_string()].into_iter().collect()),
            test_id_factory(),
        );
        let events = parser.push(
            r#"<tool_use id="native-grep" name="Grep"><parameter name="pattern">secret</parameter></tool_use>"#,
        );
        assert!(
            events.is_empty(),
            "Cursor-native Grep must not be invented as grok grep: {events:?}"
        );
        assert!(!parser.saw_tool_use());
    }
}
